languageCode = 'en-us'

copyright = 'Mobydack'
theme = 'hermit'

[author]
name = 'Kirill Zubov'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About me'
  title = 'About me'
  url = '/about'
[[menu.projects]]
  identifier = 'projects'
  name = 'Projects'
  title = 'My projects'
  url = '/projects'

[params]
showMenuItems = 10
contentTypeName = 'posts'
images = ["static/avatar.jpg"]
themeColor = '#1e1e1e'

[[params.social]]
name = 'github'
url = 'https://github.com/Mobydack'

[[params.social]]
name = 'telegram'
url = 'https://t.me/Mobydack'


[params.logo]
logoText = 'Mobydack'
